### ISSUE TITLE
Broken link to openmetrics.io on operations/metrics-over-logs

### ISSUE THREAD

**Issue by kdmcguire** [ContainerSolutions/cloud-native-patterns#14]
On operations/metrics-over-logs, the link to openmetrics.io is currently `(<https://openmetrics.io/)>`, which does not work.

Assuming that this is just a typo, shoult it be `(<https://openmetrics.io/>)`?

**Comment by cewood** [comment]
Thanks for reporting this and opening the associated PR @kdmcguire, I've just accepted and merged your fix, many thanks!
